
#define RESOURCE_ICON_CHEVRON 1
#define RESOURCE_ICON_MINIMIZE 2
#define RESOURCE_ICON_MAXIMIZE 3
#define RESOURCE_ICON_RESTORE 4
#define RESOURCE_ICON_CLOSE 5
#define RESOURCE_ICON_BOOKMARK_FILLED 6
#define RESOURCE_ICON_BOOKMARK_HOLLOW 7
